const $=s=>document.querySelector(s);
const S={token:localStorage.getItem('zx_admin_token')||'',type:'test',batch:null,batches:[]};
const API=()=>((window.ZX_CONFIG&&window.ZX_CONFIG.API_BASE)||'').replace(/\/$/,'');
async function req(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(S.token)headers.Authorization='Bearer '+S.token;const r=await fetch(API()+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Request failed');return d}
function login(){document.body.innerHTML='<div class="top"><div class="card login"><h2>Test Uploader Login</h2><label class="label">Auth Token</label><input id="tok" type="password" placeholder="Enter your auth token"><label class="label">Role</label><select><option>Batch Uploader</option></select><button class="btn full" onclick="doLogin()">Login</button></div></div>'}
async function doLogin(){try{const token=$('#tok').value.trim();if(!token)return alert('Enter your auth token');const r=await fetch(API()+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({authToken:token})});const d=await r.json();if(!r.ok)throw Error(d.message);S.token=d.token;localStorage.setItem('zx_admin_token',S.token);home()}catch(e){alert(e.message)}}
function shell(title,body){document.body.innerHTML='<div class="top"><div class="wrap"><div class="header"><h2>'+title+'</h2><button class="btn red" onclick="logout()">↪ Logout</button></div>'+body+'</div></div>'}
async function home(){try{const s=await req('/api/admin/stats');shell('Test Series Uploader','<div class="hero"><h1>Test Series<br>Uploader</h1><p>Upload and manage your test series content</p></div><div class="stats"><div class="stat">Batches<br><b>'+s.batches+'</b></div><div class="stat">Tests<br><b>'+s.tests+'</b></div><div class="stat">DPPs<br><b>'+s.dpps+'</b></div><div class="stat">Published<br><b>'+s.published+'</b></div></div><div class="tiles"><div class="tile blue" onclick="batches(\'test\')"><div class="icon">📄</div><h2>Tests</h2><p>Upload regular tests</p></div><div class="tile green" onclick="batches(\'dpp\')"><div class="icon">📚</div><h2>DPPs</h2><p>Upload daily practice problems</p></div></div>')}catch(e){logout()}}
async function batches(type){S.type=type;S.batches=(await req('/api/admin/batches')).batches||[];shell('Your Batches','<button class="btn gray" onclick="home()">← Back to Dashboard</button><div class="bar"><input id="search" placeholder="Search batches..." oninput="drawBatches()"><button class="btn green" onclick="newBatch()">+ Add Batch</button></div><div id="list"></div>');drawBatches()}
function drawBatches(){const q=($('#search')?.value||'').toLowerCase();const list=S.batches.filter(b=>b.name.toLowerCase().includes(q));$('#list').innerHTML=list.map(b=>'<div class="row"><div><b>'+esc(b.name)+'</b><small>Status: '+esc(b.status)+' • '+esc(b.language||'')+'</small></div><div class="actions"><button class="btn" onclick="content(\''+b._id+'\')">View '+(S.type==='test'?'Tests':'DPPs')+'</button><button class="btn red" onclick="delBatch(\''+b._id+'\')">Delete</button></div></div>').join('')||'<p>No batches found.</p>'}
function newBatch(){modal('<h3>Add Batch</h3><label class="label">Batch Name</label><input id="bn"><label class="label">Category</label><select id="bc"><option>Boards Level Tests</option><option>JEE Tests</option><option>NEET Tests</option><option>DROPPER Tests</option><option>Other Batch Tests</option></select><label class="label">Subgroup</label><input id="bs" placeholder="For 11th / For 12th / For NEET"><label class="label">Language</label><select id="bl"><option>Hindi</option><option>English</option><option>Hinglish</option></select><label class="label">Status</label><select id="bt"><option>Paid</option><option>Unpaid</option></select><button class="btn green full" onclick="saveBatch()">Create Batch</button>')}
async function saveBatch(){try{await req('/api/admin/batches',{method:'POST',body:JSON.stringify({name:$('#bn').value,category:$('#bc').value,subgroup:$('#bs').value,language:$('#bl').value,status:$('#bt').value})});closeModal();batches(S.type)}catch(e){alert(e.message)}}
async function delBatch(id){if(!confirm('Delete this batch and its tests/DPPs?'))return;await req('/api/admin/batches/'+id,{method:'DELETE'});batches(S.type)}
async function content(id){S.batch=S.batches.find(b=>b._id===id);const d=await req('/api/admin/batches/'+id+'/content/'+S.type);const items=d.items||[];let rows=items.map(itemRow).join('');shell('Available '+(S.type==='test'?'Tests':'DPPs'),'<button class="btn gray" onclick="batches(\''+S.type+'\')">← Back to Batches</button><button class="btn green" style="margin-left:8px" onclick="newContent()">+ Upload '+(S.type==='test'?'Test':'DPP')+'</button><div class="card"><b>'+esc(S.batch.name)+'</b><div class="notice">Progress: '+items.filter(x=>x.published).length+' / '+items.length+'</div><div id="items">'+(rows||'<p>No items yet.</p>')+'</div></div>')}
function itemRow(x){return '<div class="row"><div><b>'+esc(x.title)+'</b><small>Questions: '+(x.totalQuestions||0)+(x.startTime?' • Start Time: '+new Date(x.startTime).toLocaleString():'')+'</small></div><div class="actions">'+(x.published?'<span class="btn green">✓ Uploaded</span>':'<button class="btn" onclick="publish(\''+x._id+'\')">Upload Test</button>')+'<button class="btn red" onclick="delContent(\''+x._id+'\')">Delete</button></div></div>'}
function newContent(){modal('<h3>Upload '+(S.type==='test'?'Test':'DPP')+'</h3><label class="label">Title</label><input id="ct" placeholder="Practice Test-01"><label class="label">Start Time</label><input id="cs" type="datetime-local"><label class="label">Instructions</label><textarea id="ci"></textarea><label class="label">Questions JSON</label><textarea id="cq" placeholder="[{\"question\":\"...\",\"options\":[\"A\",\"B\",\"C\",\"D\"],\"answer\":\"A\"}]"></textarea><button class="btn green full" onclick="saveContent()">Upload '+(S.type==='test'?'Test':'DPP')+'</button>')}
async function saveContent(){try{let questions=[];if($('#cq').value.trim())questions=JSON.parse($('#cq').value);if(!Array.isArray(questions))throw Error('Questions JSON must be an array');await req('/api/admin/batches/'+S.batch._id+'/content/'+S.type,{method:'POST',body:JSON.stringify({title:$('#ct').value,startTime:$('#cs').value||null,instructions:$('#ci').value,questions,published:true})});closeModal();content(S.batch._id)}catch(e){alert(e.message)}}
async function publish(id){await req('/api/admin/content/'+id+'/publish',{method:'POST'});content(S.batch._id)}
async function delContent(id){if(!confirm('Delete this item?'))return;await req('/api/admin/content/'+id,{method:'DELETE'});content(S.batch._id)}
function modal(html){const m=document.createElement('div');m.id='modal';m.className='modal';m.innerHTML='<div class="card"><div style="text-align:right"><button class="btn gray" onclick="closeModal()">Close</button></div>'+html+'</div>';document.body.appendChild(m)}
function closeModal(){$('#modal')?.remove()}function logout(){localStorage.removeItem('zx_admin_token');S.token='';login()}function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
Object.assign(window,{doLogin,login,home,logout,batches,drawBatches,newBatch,saveBatch,delBatch,content,newContent,saveContent,publish,delContent,modal,closeModal});if(S.token)home();else login();
